<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>tia</AssemblyName>
    <RootNamespace>Tia.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <ProjectReference Include="..\Tia.Core\Tia.Core.csproj" />
    <Reference Include="Siemens.Engineering">
      <HintPath>..\..\lib\Siemens.Engineering.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
